---
# To specify a video to download in a specific directory:
- video:
  # If "name" is not present, the video name on the site will be used
  # However, specifying a name will save a lookup of to the site
  # when checking if the video is already downloaded
  name: "arduino_real_time_clock_using_the_tiny_RTC"
  url: https://www.youtube.com/watch?v=lyvoOEO-Ncg
  dir: /tmp/arduino_videos

- video:
  url: https://www.youtube.com/watch?v=Y6LKmhDRWFc
  dir: /tmp/misc

# To specify a list of videos all in the same directory:
- collection:
  # Initial path components (such as ~) are properly expanded
  dir: ~/Videos/animals
  videos:
    - video:
      # If "name" is not present, the video name on the site will be used
      name: "funny_bear"
      url: https://www.youtube.com/watch?v=mlxdnyfkWKQ
    - video:
      name: "squirrel"
      url: https://www.youtube.com/watch?v=N8lCEJo1y5g
